### PR TITLE
Inform cmake how to produce PIC code with the SYCL compiler

### PR DESCRIPTION
**Pull request by aTom3333**
Relates to #296 
Easier than I thought but I'm not sure that is the proper way to do it, seems to work fine

### CODE REVIEW

**Comment by illuhad** [comment]
Thank you!
@psalz Can you have a look?

**Comment by psalz** [comment]
The various files for the SYCL language defined here try to follow the same structure as the CXX language that comes predefined with CMake. However these mechanisms aren't well documented, so I wasn't always sure which file does what, when (and it's been a while, so I remember even less of it now). I've so far adopted a lazy approach, only porting flags from CXX to SYCL when something doesn't work.

That being said, if you take a look at your `<path/to/cmake>/Modules/CMakeCXXInformation.cmake`, you can see that the PIC-related flags are set there, so for us they should also go into `CMakeSYCLInformation.cmake` (I've tried to keep them in the same order as in the CXX file, so I think [line 184](https://github.com/illuhad/hipSYCL/blob/6c06179b5400d04150fd84926bf25d1d133b7dc5/cmake/CMakeSYCLInformation.cmake#L184) would be a good place to add this). Note that there are several additional flags for compilation and linking related to PIC/PIE defined there, so if you want to add this feature, I think it'd be best to copy all flags. Additionally, instead of hard-coding flags, so far I've usually copied the value from the corresponding `CXX` variable, for the off chance that a particular SYCL compiler uses a different flag (unlikely, but still). The `CXX` flags mostly do the same, copying the corresponding values from their `C` counterparts.

**Comment by aTom3333** [comment]
You're right, I don't how I missed the various the lines
```
if(NOT CMAKE_CXX_COMPILE_OPTIONS_PIC)
  set(CMAKE_CXX_COMPILE_OPTIONS_PIC ${CMAKE_C_COMPILE_OPTIONS_PIC})
endif()
```
and the like when looking through cmake source, I just found the definition in the compiler files (like in `<path/to/cmake>/Modules/Compiler/GNU.cmake`)
```
set(CMAKE_${lang}_COMPILE_OPTIONS_PIC "-fPIC")
```
As such i thought of those flags to be more related to the compiler than the language.

I'll make the change to forward to the CXX options and include the other PIE related ones.

**Comment by psalz** [comment]
LGTM!

**Comment by illuhad** [comment]
Thanks guys :)

**Pull request merged**
