### PR TITLE
Implement selective rewriting of includes

### PR DESCRIPTION
**Pull request by illuhad**
This implements manual selection of paths in which header files are rewritten, as discussed in issue #20. By default, everything is rewritten (as is currently the case). If `-RDI=<path>` or `--restrict-device-header-path=<path>` (names of parameter are still up for debate) are passed to `syclcc`, then a whitelist is activated, `<path>` is added to the whitelist and only include files inside of `<path>` are rewritten. At the moment, this does not yet take into account filesystem links.

If `hipsycl_transform_source` wants to modify a source that is not rewritten, a warning is emitted. This is however still disabled by default, since the warning is apparently also triggered by many files of the STL and the hipSYCL runtime. Since no changes in these files should ever be necessary, this indicates that there may be some bug in `hipsycl_transform_source`, which is best investigated in a seperate issue.

### CODE REVIEW

**Comment by psalz** [comment]
Nice! Although in addition to links, the current implementation does not correctly deal with relative paths: First, as far as I can tell the `--restrict-device-header-path` parameter does not work for something like `./include`. While I don't think it must absolutely support relative paths, compilers generally do it for their include path parameters, so it could be good for consistency.

More importantly though, something like this wouldn't work:

/some/src/file.cpp:
```c++
#include "../include/kernel.h"
```
with `--restrict-device-header-path=/some/include` (as `/some/include` is not a prefix of `../include`).

I think most if not all of these issues (including links) could be resolved with Boost::filesystem's [canonical](https://www.boost.org/doc/libs/1_67_0/libs/filesystem/doc/reference.html#canonical).

**Comment by illuhad** [comment]
Thanks for spotting this! I agree that it would be highly beneficial to support relative paths for the reasons you mentioned. I'll experiment with `boost::filesystem` this evening :)

**Comment by illuhad** [comment]
I finally had the time to implement this with `boost::filesystem::canonical`, seems to work as far as I can tell. I'm not yet sure what happens if files are included using relative paths since `syclcc` is not necessarily using the directory in which the header file is as work directory, which could cause `canonical()` to expand the path incorrectly. Whether this then works depends on what clang returns as file path of include headers (if we're lucky these are already always absolute paths)- more testing is necessary here.
It seems that at the moment Travis CI fails because it cannot find `libboost_filesystem.so`. Likely an extra package for this library must be installed in the Dockerfile.

**Comment by psalz** [comment]
I didn't have time to test this thoroughly, but I can tell you that I successfully compiled my project using this PR, without having to manually blacklist certain includes within `RewriteSelector` -- very cool! One hack less ;-).

Last time I played around with this it looked like Clang would always provide absolute paths already, but you could of course add a sanity check with `boost::filesystem::path::is_relative`!

For Travis I think you might need `libboost-all-dev` or simply `libboost-filesystem-dev`.

**Comment by illuhad** [comment]
Thanks for the feedback! It should now print a warning when clang returns a relative path, as you suggested. I have also fixed the Travis builds :) I'll merge this PR tomorrow if no further issues pop up.

**Pull request merged**
