### PR TITLE
Update SYCL targets image

### PR DESCRIPTION
**Pull request by illuhad**
Update SYCL targets image to reflect current status of SYCL implementations

### CODE REVIEW

**Comment by fodinabor** [comment]
I think you can remove the ? from other OpenCL SPIR-V devices for Intel SYCL implementation. They seem to support anything that has OpenCL 1.2 and SPIR-V support.. (also theoretically other targets if using another backend than spir-unknown-unknown)
They do also support Intel FPGAs.

**Comment by illuhad** [comment]
thanks, I think I've added the ? because pretty much the only vendor supporting OpenCL SPIR-V ingestion is Intel, so in practice it's not clear if there are other devices.. Maybe we can just remove the entire line because it's pure speculation. Will add Intel FPGA, thanks!

**Comment by fodinabor** [comment]
I _think_ AMD on ROCm supports SPIR-V, too.. Didn't check again though.

Fri Nov 15 13:47:31 GMT+01:00 2019 Aksel Alpay <notifications@github.com>:

**Comment by illuhad** [comment]
Added Intel FPGA, layout changes, changed color schemes to better match implementations/implementors.

If ROCm supports SPIR-V now, it must be a very new (and probably experimental) feature. I'm sure they didn't a few months ago. The lack of SPIR-V support is also why some people where not so happy when AMD dropped SPIR in ROCm support since it prevented ComputeCpp from working..

**Comment by fodinabor** [comment]
Yeah.. I See.. Was a bit out of date then.. And probably mixed spir and spir-v

Fri Nov 15 14:22:07 GMT+01:00 2019 Aksel Alpay <notifications@github.com>:

**Comment by keryell** [comment]
@illuhad I let you tweet this image again... :-)

**Pull request merged**
