### PR TITLE
Allow simple swizzles for vec<T, N> to vec<T, N-n>

### PR DESCRIPTION
**Pull request by fodinabor**
As discussed in #7.

I could not really test it, yet though (only Windows here..)
The CI pipeline should maybe be extended to actually run the tests? ;-)

### CODE REVIEW

**Comment by illuhad** [comment]
Thank you! However the unit tests won't compile:
```
/hipSYCL/tests/unit_tests.cpp:351:22: error: no matching member function for call to 'xyy'
      v11.xzw() = v8.xyy();
                  ~~~^~~
/usr/bin/../include/CL/sycl/vec.hpp:398:34: note: candidate template ignored: requirement '4 == 3' was not satisfied [with n = 4]
  HIPSYCL_DEFINE_VECTOR_SWIZZLE3(xyy, 0, 1, 1)
                                 ^
/hipSYCL/tests/unit_tests.cpp:351:11: error: no member named 'xzw' in 'cl::sycl::vec<float, 4>'
      v11.xzw() = v8.xyy();
      ~~~ ^
/hipSYCL/tests/unit_tests.cpp:355:11: error: no member named 'zy' in 'cl::sycl::vec<float, 4>'
      v12.zy() = v8.hi();
      ~~~ ^

```
The first error is because you also actually need to change the definition of the swizzles in the `vec<>` class itself - you have only changed the definition in the temporary swizzle objects (we may want to unify those in order to not have those swizzle definitions twice..)

The last two errors are caused by the fact that e.g. for the 2-component swizzles, we currently only have defined all permutations of `(x,y)`, but now we also need to define all two-component permutations of `(x,y,z,w)`. The same holds for the 3-component swizzles.

You are of course absolutely right with your point about the unit tests in the CI pipeline - the main issue here is that we ideally would like to run the unit tests on GPUs as well (ideally, both NVIDIA and AMD) which we don't have in Travis CI. At the moment, I'm working towards building a test infrastructure that we can use in the future for that purpose, but it will still take some time until I have all the hardware and it is integrated into the github workflow etc :)

**Comment by fodinabor** [comment]
The thing about the CI pipeline sounds awesome :)

I think I got all covered now..

**Comment by illuhad** [comment]
Thank you, compiles fine now :) I do get some test failures though:
```
Running unit tests hipSYCL/CUDA...
Running 34 test cases...
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [2.29877604e-38 != 1]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [0 != 3]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [2.30995644e-38 != 4]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [0 != 4]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [1.97512213e-13 != 3]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [5.18480432e-44 != 2]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [4.27396032e-43 != 1]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [0 != 3]

*** 8 failures are detected in the test module "hipsycl unit tests"
```
While unfortunately it only points to the declaration of the `verify_results` lambda, it is clear from the sequence of expected results that these are the new tests that are failing. From the looks of it, could be accesses to uninitialized memory. Likely the results buffer in line 296 of `unit_tests.cpp` is simply not of sufficient size to hold the new test results (which would also match the appearance of uninitialized memory). Could you please check what the new required minimum size of that buffer has to be?

**Comment by illuhad** [comment]
Great! Only issue remaining is:
```
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [1 != 2]
/hipSYCL/tests/unit_tests.cpp(364): error: in "device_test_suite/vec_api": check acc[offset++] == e has failed [2 != 1]
```
This looks like some semantic error, e.g. a typo in the swizzle indices..

**Comment by illuhad** [comment]
Wonderful, working perfectly now :) Thank you!

**Pull request merged**
