### PR TITLE
Implementing hidden friends

### PR DESCRIPTION
**Pull request by sbalint98**
Implementing spec maintenance change described in issue #173 (https://github.com/KhronosGroup/SYCL-Docs/pull/42)

### CODE REVIEW

**Comment by illuhad** [comment]
there are a lot of merge conflicts, probably because of the move to the new code structure. Can you resolve them, please?

**Comment by sbalint98** [comment]
Oh sorry. they are resolved now.

**Comment by illuhad** [comment]
I *think* this is good, but would like to play some more with it due to the size of the changes.

**Comment by psalz** [comment]
I just noticed that `accessor` seems to be missing both of the equality operators altogether. Maybe this could also be added here..? :)

**Comment by illuhad** [comment]
Thank you!

**Pull request merged**
