### PR TITLE
Added updated install script for aomp 11.6-1

### PR DESCRIPTION
**Pull request by sbalint98**
This pull request updates the install scripts in order to accommodate the update for clang 10 and for ROCm 3.5 with the newest aomp release. 

The updated packages are available under the: http://repo.urz.uni-heidelberg.de/sycl/test_llvm10_rocm11/ link for the supported distros. Please note that these packages are experimental, and they need to be tested before merging this PR. 

Furthermore, it contains minor fixes for the packaging system

### CODE REVIEW

**Comment by illuhad** [comment]
It seems this is affected by the `hipStreamAddCallback` crash from issue #265

**Comment by illuhad** [comment]
Following the discussion in #265, we either need to wait for ROCm 3.6 or try an earlier ROCm version since AMD has now confirmed that `hipStreamAddCallback` is broken for the default stream in ROCm 3.5.

**Comment by illuhad** [comment]
@sbalint98 How would you like to proceed? Downgrade to earlier ROCm/aomp?

**Comment by sbalint98** [comment]
Sure that seems like a good way to proceed in my opinion. It used to work with the one earlier release (which pulls from rocm-3.3 ) but it needed a lot of tweaking. I will have a look

**Comment by illuhad** [comment]
Closing now, please file new PR with different ROCm version :) Also, because of PR #281 we should really push out clang 10 now...

**Pull request closed without merging**
